TA-2085 Update Cypress Interview (Live Coding Exercise)
Freshly/cypress-interview pull request #2
Opened 2022-06-06 15:56 UTC by jimmyadames

## [TA-2085](https://freshly.atlassian.net/browse/TA-2085)

## What's this PR do?
- Upgraded Cypress to `10.0.2`
- Added a .gitignore file
- Created spec file `homepage.cy.js` based on the previous exercise

## Where should the reviewer start?
The majority of the file changes come from adding the node_modules folder to the `.gitignore` file the other changes (mainly the Cypress directories) are changes from the version upgrade. For more context on the upgrade, feel free to look at the [migration guide](https://docs.cypress.io/guides/references/migration-guide).

## How should this be manually tested?
- Run the specs locally and feel free to work on the exercises to get the tests passing. We could always tweak this to be more challenging.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist

- [x] The title of this PR is the same as the story.
- [x] The pull request is < 1000 LOC.
- [x] I have written specs/coverage where required.
- [x] I have tested this myself.
- [x] I have added all necessary labels (trivial, WIP, requires QA, review, etc).
- [x] I have added the correct milestone
- [x] I have cleaned up redundant template boilerplate from this PR description.

---
More info about our code review process — [Code Review](https://engineering.freshlyhq.com/02_processes/03_software_development/03_code_review.html)

2022-06-10 15:16 UTC, jar145 approved these changes

2022-06-28 08:12 UTC, halinaVabishchevich requested changes

2022-06-28 08:12 UTC, halinaVabishchevich commented on .gitignore
> +node_modules
change to /node_modules
all modules where commited 
![image](https://user-images.githubusercontent.com/90702282/176128603-1349ba67-2259-4ea7-bcba-c5cc8cf53b3d.png)

2022-07-01 15:58 UTC, halinaVabishchevich approved these changes

2022-07-05 16:00 UTC, merged